export const defaultContent = {
  brand: {
    name: "Camp 3GRT",
    tagline: "Muaythai School Garut",
    logo: "/images/logo.svg",
  },
  hero: {
    badge: "Buka Setiap Hari 09.00–22.00 WIB",
    titleTop: "LATIHAN KERAS,",
    titleBottom: "DISIPLIN, JUARA!",
    subtitle: "Pusat latihan Muay Thai profesional di Garut. Dari pemula hingga atlet, kami siap membimbingmu.",
    ctaPrimary: "Daftar via WhatsApp",
    ctaSecondary: "Lihat Program",
    bgImage: "/images/coach-dio.jpg",
  },
  values: ["Disiplin", "Fokus", "Kekuatan", "Konsistensi", "Respek", "Semangat", "Juara"],
  about: {
    heading: "Tentang Camp 3GRT",
    lead: "Camp 3GRT adalah pusat latihan Muay Thai profesional di Garut, Jawa Barat.",
    body: "Didirikan dengan semangat membawa seni bela diri Muay Thai ke Garut, Camp 3GRT hadir untuk semua kalangan — dari anak-anak, remaja, hingga dewasa. Kami memiliki coach berpengalaman dan fasilitas lengkap untuk mendukung perjalanan latihanmu.",
    image: "/images/coach-dio.jpg",
    stats: [
      { value: "5+", label: "Tahun Berdiri" },
      { value: "200+", label: "Member Aktif" },
      { value: "10+", label: "Coach Terlatih" },
      { value: "50+", label: "Atlet Juara" },
    ],
  },
  programs: [
    { id: "p1", name: "Group Training", desc: "Latihan bersama dalam kelompok yang seru dan penuh semangat. Cocok untuk semua level.", level: "Semua Level", icon: "users" },
    { id: "p2", name: "Personal Training", desc: "Sesi privat satu-satu dengan coach untuk kemajuan yang lebih cepat dan terarah.", level: "Semua Level", icon: "target" },
    { id: "p3", name: "Muay Kids", desc: "Program khusus anak-anak usia 6–14 tahun. Membangun disiplin, fokus, dan kepercayaan diri.", level: "Anak-Anak", icon: "child" },
    { id: "p4", name: "Private Class", desc: "Kelas privat dengan jadwal fleksibel sesuai kesibukanmu.", level: "Semua Level", icon: "star" },
  ],
  coaches: [
    {
      id: "c1",
      name: "Coach Dio",
      role: "Head Coach",
      bio: "Coach Dio adalah pelatih kepala Camp 3GRT dengan pengalaman lebih dari 10 tahun di dunia Muay Thai. Telah melatih ratusan atlet dari berbagai daerah.",
      image: "/images/coach-dio.jpg",
      specialties: ["Teknik Dasar", "Sparring", "Kondisi Fisik"],
    },
  ],
  schedule: [
    { day: "Senin", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Group Training", coach: "Coach Dio" }] },
    { day: "Selasa", sessions: [{ time: "09.00–11.00", name: "Personal Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Muay Kids", coach: "Coach Dio" }] },
    { day: "Rabu", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Group Training", coach: "Coach Dio" }] },
    { day: "Kamis", sessions: [{ time: "09.00–11.00", name: "Personal Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Group Training", coach: "Coach Dio" }] },
    { day: "Jumat", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Muay Kids", coach: "Coach Dio" }] },
    { day: "Sabtu", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "14.00–16.00", name: "Sparring", coach: "Coach Dio" }] },
    { day: "Minggu", sessions: [] },
  ],
  pricing: [
    {
      id: "pr1",
      name: "Paket Trial",
      desc: "Coba latihan pertama kamu tanpa risiko.",
      price: "50.000",
      period: "/ 1 sesi",
      popular: false,
      cta: "Coba Sekarang",
      features: ["1 sesi latihan", "Dipandu coach", "Tanpa kontrak"],
    },
    {
      id: "pr2",
      name: "Member Bulanan",
      desc: "Latihan rutin dengan harga terjangkau.",
      price: "300.000",
      period: "/ bulan",
      popular: true,
      cta: "Pilih Paket Ini",
      features: ["Latihan tidak terbatas", "Akses semua sesi", "Dipandu coach", "Loker tersedia"],
    },
    {
      id: "pr3",
      name: "Paket 3 Bulan",
      desc: "Hemat lebih banyak dengan komitmen 3 bulan.",
      price: "800.000",
      period: "/ 3 bulan",
      popular: false,
      cta: "Pilih Paket",
      features: ["Latihan tidak terbatas", "Akses semua sesi", "Dipandu coach", "Loker tersedia", "Hemat 11%"],
    },
  ],
  testimonials: [
    { id: "t1", name: "Andi S.", role: "Member Aktif", quote: "Latihan di Camp 3GRT benar-benar mengubah hidupku. Fisik lebih kuat, mental lebih tangguh!", rating: 5 },
    { id: "t2", name: "Siti R.", role: "Member Muay Kids", quote: "Anak saya jadi lebih disiplin dan percaya diri setelah ikut Muay Kids di sini.", rating: 5 },
    { id: "t3", name: "Budi H.", role: "Member 6 Bulan", quote: "Coach-nya sabar dan profesional. Teknik saya berkembang pesat dalam waktu singkat.", rating: 5 },
  ],
  gallery: [
    { image: "/images/coach-dio.jpg", caption: "Sesi latihan bersama" },
    { image: "/images/coach-dio.jpg", caption: "Sparring session" },
    { image: "/images/coach-dio.jpg", caption: "Muay Kids class" },
  ],
  faq: [
    { q: "Apakah harus punya pengalaman Muay Thai dulu?", a: "Tidak perlu! Kami menerima pemula dari nol. Coach kami akan membimbing dari teknik dasar." },
    { q: "Berapa usia minimal untuk bergabung?", a: "Untuk kelas Muay Kids minimal 6 tahun. Untuk kelas dewasa minimal 15 tahun." },
    { q: "Apakah tersedia kelas untuk wanita?", a: "Tentu! Kami memiliki member wanita dan suasana latihan sangat nyaman dan aman." },
    { q: "Bagaimana cara mendaftar?", a: "Hubungi kami via WhatsApp atau isi form di bagian Kontak. Tim kami akan menghubungi kamu." },
    { q: "Apakah harus membawa perlengkapan sendiri?", a: "Untuk trial, kamu tidak perlu membawa apa-apa. Kami menyediakan perlengkapan dasar. Untuk member, disarankan punya sarung tinju sendiri." },
  ],
  contact: {
    phone: "0895-2437-8203",
    whatsapp: "6289524378203",
    address: "Garut, Jawa Barat",
    hoursWeekday: "Setiap Hari 09.00–22.00 WIB",
    mapsEmbed: "",
    instagram: "",
    tiktok: "",
    facebook: "",
    youtube: "",
  },
};
