export const defaultContent = {
  brand: {
    name: "Camp 3GRT",
    tagline: "Muaythai School Garut",
    logo: "/images/logo.svg",
  },
  hero: {
    badge: "Buka Setiap Hari 09.00–22.00 WIB",
    titleTop: "LATIHAN KERAS,",
    titleBottom: "DISIPLIN, JUARA!",
    subtitle: "Pusat latihan Muay Thai profesional di Garut. Dari pemula hingga atlet, kami siap membimbingmu.",
    ctaPrimary: "Daftar via WhatsApp",
    ctaSecondary: "Lihat Program",
    bgImage: "/images/coach-dio.jpg",
    badgeEn: "Open Every Day 09:00–22:00 WIB",
    titleTopEn: "TRAIN HARD,",
    titleBottomEn: "DISCIPLINE, CHAMPION!",
    subtitleEn: "Professional Muay Thai training center in Garut. From beginners to athletes, we're here to guide you.",
    ctaPrimaryEn: "Register via WhatsApp",
    ctaSecondaryEn: "View Programs",
  },
  values: ["Disiplin", "Fokus", "Kekuatan", "Konsistensi", "Respek", "Semangat", "Juara"],
  valuesEn: ["Discipline", "Focus", "Strength", "Consistency", "Respect", "Spirit", "Champion"],
  about: {
    heading: "Tentang Camp 3GRT",
    lead: "Camp 3GRT adalah pusat latihan Muay Thai profesional di Garut, Jawa Barat.",
    body: "Didirikan dengan semangat membawa seni bela diri Muay Thai ke Garut, Camp 3GRT hadir untuk semua kalangan — dari anak-anak, remaja, hingga dewasa. Kami memiliki coach berpengalaman dan fasilitas lengkap untuk mendukung perjalanan latihanmu.",
    image: "/images/coach-dio.jpg",
    stats: [
      { value: "5+", label: "Tahun Berdiri", labelEn: "Years Standing" },
      { value: "200+", label: "Member Aktif", labelEn: "Active Members" },
      { value: "10+", label: "Coach Terlatih", labelEn: "Trained Coaches" },
      { value: "50+", label: "Atlet Juara", labelEn: "Champion Athletes" },
    ],
    headingEn: "About Camp 3GRT",
    leadEn: "Camp 3GRT is a professional Muay Thai training center in Garut, West Java.",
    bodyEn: "Founded with a passion to bring Muay Thai martial arts to Garut, Camp 3GRT is open to everyone — from children, teenagers, to adults. We have experienced coaches and complete facilities to support your training journey.",
  },
  programs: [
    { id: "p1", name: "Group Training", nameEn: "Group Training", desc: "Latihan bersama dalam kelompok yang seru dan penuh semangat. Cocok untuk semua level.", descEn: "Fun and energetic group training sessions suitable for all levels.", level: "Semua Level", levelEn: "All Levels", icon: "users" },
    { id: "p2", name: "Personal Training", nameEn: "Personal Training", desc: "Sesi privat satu-satu dengan coach untuk kemajuan yang lebih cepat dan terarah.", descEn: "One-on-one private sessions with a coach for faster and more focused progress.", level: "Semua Level", levelEn: "All Levels", icon: "target" },
    { id: "p3", name: "Muay Kids", nameEn: "Muay Kids", desc: "Program khusus anak-anak usia 6–14 tahun. Membangun disiplin, fokus, dan kepercayaan diri.", descEn: "Special program for children aged 6–14. Building discipline, focus, and self-confidence.", level: "Anak-Anak", levelEn: "Children", icon: "child" },
    { id: "p4", name: "Private Class", nameEn: "Private Class", desc: "Kelas privat dengan jadwal fleksibel sesuai kesibukanmu.", descEn: "Private class with flexible scheduling to fit your busy lifestyle.", level: "Semua Level", levelEn: "All Levels", icon: "star" },
  ],
  coaches: [
    {
      id: "c1",
      name: "Coach Dio",
      role: "Head Coach",
      roleEn: "Head Coach",
      bio: "Coach Dio adalah pelatih kepala Camp 3GRT dengan pengalaman lebih dari 10 tahun di dunia Muay Thai. Telah melatih ratusan atlet dari berbagai daerah.",
      bioEn: "Coach Dio is the head coach of Camp 3GRT with over 10 years of experience in Muay Thai. He has trained hundreds of athletes from various regions.",
      image: "/images/coach-dio.jpg",
      specialties: ["Teknik Dasar", "Sparring", "Kondisi Fisik"],
      specialtiesEn: ["Basic Techniques", "Sparring", "Physical Conditioning"],
    },
  ],
  schedule: [
    { day: "Senin", dayEn: "Monday", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Group Training", coach: "Coach Dio" }] },
    { day: "Selasa", dayEn: "Tuesday", sessions: [{ time: "09.00–11.00", name: "Personal Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Muay Kids", coach: "Coach Dio" }] },
    { day: "Rabu", dayEn: "Wednesday", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Group Training", coach: "Coach Dio" }] },
    { day: "Kamis", dayEn: "Thursday", sessions: [{ time: "09.00–11.00", name: "Personal Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Group Training", coach: "Coach Dio" }] },
    { day: "Jumat", dayEn: "Friday", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "17.00–19.00", name: "Muay Kids", coach: "Coach Dio" }] },
    { day: "Sabtu", dayEn: "Saturday", sessions: [{ time: "09.00–11.00", name: "Group Training", coach: "Coach Dio" }, { time: "14.00–16.00", name: "Sparring", coach: "Coach Dio" }] },
    { day: "Minggu", dayEn: "Sunday", sessions: [] },
  ],
  pricing: [
    {
      id: "pr1",
      name: "Paket Trial", nameEn: "Trial Package",
      desc: "Coba latihan pertama kamu tanpa risiko.", descEn: "Try your first training session with no risk.",
      price: "50.000", period: "/ 1 sesi",
      popular: false,
      cta: "Coba Sekarang", ctaEn: "Try Now",
      features: ["1 sesi latihan", "Dipandu coach", "Tanpa kontrak"],
      featuresEn: ["1 training session", "Coach-guided", "No contract"],
    },
    {
      id: "pr2",
      name: "Member Bulanan", nameEn: "Monthly Member",
      desc: "Latihan rutin dengan harga terjangkau.", descEn: "Regular training at an affordable price.",
      price: "300.000", period: "/ bulan",
      popular: true,
      cta: "Pilih Paket Ini", ctaEn: "Choose This Package",
      features: ["Latihan tidak terbatas", "Akses semua sesi", "Dipandu coach", "Loker tersedia"],
      featuresEn: ["Unlimited training", "Access to all sessions", "Coach-guided", "Locker available"],
    },
    {
      id: "pr3",
      name: "Paket 3 Bulan", nameEn: "3-Month Package",
      desc: "Hemat lebih banyak dengan komitmen 3 bulan.", descEn: "Save more with a 3-month commitment.",
      price: "800.000", period: "/ 3 bulan",
      popular: false,
      cta: "Pilih Paket", ctaEn: "Choose Package",
      features: ["Latihan tidak terbatas", "Akses semua sesi", "Dipandu coach", "Loker tersedia", "Hemat 11%"],
      featuresEn: ["Unlimited training", "Access to all sessions", "Coach-guided", "Locker available", "Save 11%"],
    },
  ],
  testimonials: [
    { id: "t1", name: "Andi S.", role: "Member Aktif", roleEn: "Active Member", quote: "Latihan di Camp 3GRT benar-benar mengubah hidupku. Fisik lebih kuat, mental lebih tangguh!", quoteEn: "Training at Camp 3GRT has truly changed my life. Stronger physically, tougher mentally!", rating: 5 },
    { id: "t2", name: "Siti R.", role: "Member Muay Kids", roleEn: "Muay Kids Member", quote: "Anak saya jadi lebih disiplin dan percaya diri setelah ikut Muay Kids di sini.", quoteEn: "My child became more disciplined and confident after joining Muay Kids here.", rating: 5 },
    { id: "t3", name: "Budi H.", role: "Member 6 Bulan", roleEn: "6-Month Member", quote: "Coach-nya sabar dan profesional. Teknik saya berkembang pesat dalam waktu singkat.", quoteEn: "The coaches are patient and professional. My technique improved rapidly in a short time.", rating: 5 },
  ],
  gallery: [
    { image: "/images/coach-dio.jpg", caption: "Sesi latihan bersama", captionEn: "Group training session" },
    { image: "/images/coach-dio.jpg", caption: "Sparring session", captionEn: "Sparring session" },
    { image: "/images/coach-dio.jpg", caption: "Muay Kids class", captionEn: "Muay Kids class" },
  ],
  faq: [
    { q: "Apakah harus punya pengalaman Muay Thai dulu?", a: "Tidak perlu! Kami menerima pemula dari nol. Coach kami akan membimbing dari teknik dasar.", qEn: "Do I need prior Muay Thai experience?", aEn: "Not at all! We accept complete beginners. Our coaches will guide you from the basics." },
    { q: "Berapa usia minimal untuk bergabung?", a: "Untuk kelas Muay Kids minimal 6 tahun. Untuk kelas dewasa minimal 15 tahun.", qEn: "What is the minimum age to join?", aEn: "For Muay Kids classes, minimum 6 years old. For adult classes, minimum 15 years old." },
    { q: "Apakah tersedia kelas untuk wanita?", a: "Tentu! Kami memiliki member wanita dan suasana latihan sangat nyaman dan aman.", qEn: "Are classes available for women?", aEn: "Absolutely! We have female members and the training environment is very comfortable and safe." },
    { q: "Bagaimana cara mendaftar?", a: "Hubungi kami via WhatsApp atau isi form di bagian Kontak. Tim kami akan menghubungi kamu.", qEn: "How do I register?", aEn: "Contact us via WhatsApp or fill out the form in the Contact section. Our team will reach out to you." },
    { q: "Apakah harus membawa perlengkapan sendiri?", a: "Untuk trial, kamu tidak perlu membawa apa-apa. Kami menyediakan perlengkapan dasar. Untuk member, disarankan punya sarung tinju sendiri.", qEn: "Do I need to bring my own equipment?", aEn: "For a trial session, you don't need anything. We provide basic equipment. For members, it's recommended to have your own boxing gloves." },
  ],
  partners: [],
  contact: {
    phone: "0895-2437-8203",
    whatsapp: "6289524378203",
    address: "Garut, Jawa Barat",
    addressEn: "Garut, West Java",
    hoursWeekday: "Setiap Hari 09.00–22.00 WIB",
    hoursWeekdayEn: "Every Day 09:00–22:00 WIB",
    mapsEmbed: "",
    instagram: "",
    tiktok: "",
    facebook: "",
    youtube: "",
  },
};
